const $ = (id) => document.getElementById(id);
const fields = ['JARVIS_AGENT_ENABLED','JARVIS_CONVERSATION_MODE','JARVIS_WAKE_PROMPT','JARVIS_CHROME_URL','JARVIS_YOUTUBE_URL','JARVIS_STT_PROVIDER','JARVIS_STT_LANGUAGE','JARVIS_VAD_THRESHOLD','JARVIS_VAD_SILENCE_SECONDS'];
let particles = [];
const canvas = $('orb'), ctx = canvas.getContext('2d');
function resize(){const d=devicePixelRatio||1; const r=canvas.getBoundingClientRect(); canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0); particles=Array.from({length:170},()=>({a:Math.random()*Math.PI*2,r:75+Math.random()*63,s:.001+Math.random()*.003,o:Math.random()*6.28}));} window.addEventListener('resize',resize); resize();
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,cx=w/2,cy=h/2,busy=$('stateLabel').textContent==='ACTIVE';ctx.clearRect(0,0,w,h);particles.forEach(p=>{p.a+=p.s*(busy?3:1);const pulse=busy?Math.sin(Date.now()/180+p.o)*8:Math.sin(Date.now()/900+p.o)*3;const rr=p.r+pulse, x=cx+Math.cos(p.a)*rr,y=cy+Math.sin(p.a)*rr;ctx.fillStyle=`hsla(${busy?174:75},${busy?85:75}%,${busy?68:61}%,${.25+Math.abs(Math.sin(p.o))* .55})`;ctx.fillRect(x,y,busy?2:1.3,busy?2:1.3)});requestAnimationFrame(draw)} draw();
async function api(path, options={}){const started=performance.now();const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await r.json();$('latency').textContent=Math.round(performance.now()-started);if(!r.ok)throw Error(data.error||'Request failed');return data}
function fillSettings(s){fields.forEach(id=>{const e=$(id);if(e.type==='checkbox')e.checked=Boolean(s[id]);else e.value=s[id]??''});$('thresholdOutput').textContent=Number(s.JARVIS_VAD_THRESHOLD||0).toFixed(3);$('silenceOutput').textContent=`${Number(s.JARVIS_VAD_SILENCE_SECONDS||0).toFixed(1)}s`}
async function load(){try{const d=await api('/api/settings');fillSettings(d.settings);$('connectionText').textContent='LOCAL LINK / ONLINE'}catch(e){$('connectionText').textContent='LINK ERROR'}}
function speakResponse(text){if('speechSynthesis' in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=$('JARVIS_STT_LANGUAGE').value||'ko-KR';utterance.rate=.96;speechSynthesis.speak(utterance)}}
async function send(command){$('command').value=command;$('response').classList.add('loading');$('response').innerHTML='<span class="response-dot"></span><span>자비스가 처리 중입니다...</span>';try{const d=await api('/api/command',{method:'POST',body:JSON.stringify({command})});$('response').innerHTML=`<span class="response-dot"></span><span>${d.response}</span>`;speakResponse(d.response)}catch(e){$('response').innerHTML=`<span class="response-dot"></span><span>${e.message}</span>`}finally{$('response').classList.remove('loading')}}
let recognition;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(Recognition){recognition=new Recognition();recognition.lang='ko-KR';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{$('voiceButton').classList.add('listening');$('voiceButton').innerHTML='<span>◉</span> LISTENING';$('stateLabel').textContent='LISTENING';$('stateHint').textContent='SPEAK YOUR COMMAND'};recognition.onresult=e=>{const text=Array.from(e.results).map(r=>r[0].transcript).join('');$('command').value=text;if(e.results[e.results.length-1].isFinal)send(text)};recognition.onerror=e=>{$('response').innerHTML=`<span class="response-dot"></span><span>마이크를 사용할 수 없습니다: ${e.error}</span>`};recognition.onend=()=>{$('voiceButton').classList.remove('listening');$('voiceButton').innerHTML='<span>◉</span> LISTEN';$('stateLabel').textContent='STANDBY';$('stateHint').textContent='DOUBLE CLAP READY'}}else{$('voiceButton').disabled=true;$('voiceButton').title='이 브라우저는 음성 인식을 지원하지 않습니다'}
$('commandForm').addEventListener('submit',e=>{e.preventDefault();send($('command').value)});document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.command)));$('command').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.target.value)}});$('voiceButton').addEventListener('click',()=>{if(!recognition)return;if($('voiceButton').classList.contains('listening'))recognition.stop();else{recognition.lang=$('JARVIS_STT_LANGUAGE').value||'ko-KR';recognition.start()}});$('JARVIS_VAD_THRESHOLD').addEventListener('input',e=>$('thresholdOutput').textContent=Number(e.target.value).toFixed(3));$('JARVIS_VAD_SILENCE_SECONDS').addEventListener('input',e=>$('silenceOutput').textContent=`${Number(e.target.value).toFixed(1)}s`);
$('saveSettings').addEventListener('click',async()=>{const payload={};fields.forEach(id=>{const e=$(id);payload[id]=e.type==='checkbox'?e.checked:e.value});try{await api('/api/settings',{method:'POST',body:JSON.stringify(payload)});$('saveSettings').textContent='SAVED';setTimeout(()=>$('saveSettings').textContent='SAVE',1400)}catch(e){$('saveSettings').textContent='ERROR'}});
async function status(){try{const d=await api('/api/status');const active=d.state==='busy';$('stateLabel').textContent=active?'ACTIVE':'STANDBY';$('stateHint').textContent=active?'PROCESSING VOICE SESSION':'DOUBLE CLAP READY';$('signal').textContent=active?'100':'98';$('clock').textContent=new Date().toLocaleTimeString('en-GB')}catch(e){}}load();status();setInterval(status,1800);