const $ = (id) => document.getElementById(id);
const fields = ['JARVIS_AGENT_ENABLED','JARVIS_CONVERSATION_MODE','JARVIS_WAKE_PROMPT','JARVIS_CHROME_URL','JARVIS_YOUTUBE_URL','JARVIS_STT_PROVIDER','JARVIS_STT_LANGUAGE','JARVIS_VAD_THRESHOLD','JARVIS_VAD_SILENCE_SECONDS'];
let requestPending = false;
let particles = [];
const canvas = $('orb'), ctx = canvas.getContext('2d');
function resize(){const d=devicePixelRatio||1; const r=canvas.getBoundingClientRect(); canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0); particles=Array.from({length:170},()=>({a:Math.random()*Math.PI*2,r:75+Math.random()*63,s:.001+Math.random()*.003,o:Math.random()*6.28}));} window.addEventListener('resize',resize); resize();
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,cx=w/2,cy=h/2,loading=requestPending,speaking=$('orbWrap').classList.contains('speaking');ctx.clearRect(0,0,w,h);particles.forEach(p=>{p.a+=p.s*(loading?5:speaking?2:1);const pulse=loading?Math.sin(Date.now()/120+p.o)*4:speaking?Math.sin(Date.now()/90+p.o)*18:Math.sin(Date.now()/900+p.o)*3;const rr=p.r+pulse, x=cx+Math.cos(p.a)*rr,y=cy+Math.sin(p.a)*rr;ctx.fillStyle=`hsla(${loading?40:speaking?174:75},${loading||speaking?85:75}%,${loading||speaking?68:61}%,${.25+Math.abs(Math.sin(p.o))* .55})`;ctx.fillRect(x,y,loading||speaking?2:1.3,loading||speaking?2:1.3)});requestAnimationFrame(draw)} draw();
async function api(path, options={}){const started=performance.now();const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await r.json();$('latency').textContent=Math.round(performance.now()-started);if(!r.ok)throw Error(data.error||'Request failed');return data}
function renderList(id, items, formatter){const element=$(id);element.textContent='';(items||[]).forEach(item=>{const row=document.createElement('div');row.className='runtime-row';row.textContent=formatter(item);element.appendChild(row)});if(!items||!items.length)element.textContent='없음'}
async function loadRuntime(){try{const [agents,providers,models,tasks,memory]=await Promise.all([api('/api/agents'),api('/api/providers'),api('/api/models'),api('/api/tasks'),api('/api/memory')]);renderList('agentsPanel',agents.agents,a=>`${a.role.toUpperCase()} · ${a.tools.join(', ')}`);renderList('providersPanel',providers.providers,p=>`${p.id.toUpperCase()} · ${p.status}`);renderList('modelsPanel',models.models,m=>`${m.provider} / ${m.name} · ${m.local?'LOCAL':'CLOUD'}`);renderList('tasksPanel',tasks.tasks,t=>`${t.status.toUpperCase()} · ${t.prompt}`);renderList('memoryPanel',memory.memory,m=>`MEMORY · ${m.content}`)}catch(e){['agentsPanel','providersPanel','modelsPanel','tasksPanel','memoryPanel'].forEach(id=>$(id).textContent='연결 오류')}}}
function fillSettings(s){fields.forEach(id=>{const e=$(id);if(e.type==='checkbox')e.checked=Boolean(s[id]);else e.value=s[id]??''});$('thresholdOutput').textContent=Number(s.JARVIS_VAD_THRESHOLD||0).toFixed(3);$('silenceOutput').textContent=`${Number(s.JARVIS_VAD_SILENCE_SECONDS||0).toFixed(1)}s`}
async function load(){try{const d=await api('/api/settings');fillSettings(d.settings);$('connectionText').textContent='LOCAL LINK / ONLINE'}catch(e){$('connectionText').textContent='LINK ERROR'}}
async function send(command, speak=true){command=command.trim();if(!command)return;$('command').value=command;requestPending=true;$('orbWrap').classList.add('loading');$('response').classList.add('loading');$('response').innerHTML='<span class="response-dot"></span><span>자비스가 처리 중입니다...</span>';try{const d=await api('/api/command',{method:'POST',body:JSON.stringify({command,speak})});$('response').innerHTML=`<span class="response-dot"></span><span>${d.response}</span>`}catch(e){$('response').innerHTML=`<span class="response-dot"></span><span>${e.message}</span>`}finally{requestPending=false;$('orbWrap').classList.remove('loading');$('response').classList.remove('loading')}}
let recognition;const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(Recognition){recognition=new Recognition();recognition.lang='ko-KR';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{$('voiceButton').classList.add('listening');$('voiceButton').innerHTML='<span>◉</span> LISTENING';$('stateLabel').textContent='LISTENING';$('stateHint').textContent='SPEAK YOUR COMMAND'};recognition.onresult=e=>{const text=Array.from(e.results).map(r=>r[0].transcript).join('');$('command').value=text;if(e.results[e.results.length-1].isFinal)send(text)};recognition.onerror=e=>{$('response').innerHTML=`<span class="response-dot"></span><span>마이크를 사용할 수 없습니다: ${e.error}</span>`};recognition.onend=()=>{$('voiceButton').classList.remove('listening');$('voiceButton').innerHTML='<span>◉</span> LISTEN';$('stateLabel').textContent='STANDBY';$('stateHint').textContent='DOUBLE CLAP READY'}}else{$('voiceButton').disabled=true;$('voiceButton').title='이 브라우저는 음성 인식을 지원하지 않습니다'}
$('commandForm').addEventListener('submit',e=>{e.preventDefault();send($('command').value)});document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.command)));$('command').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.target.value)}});$('voiceButton').addEventListener('click',()=>{if(!recognition)return;if($('voiceButton').classList.contains('listening'))recognition.stop();else{recognition.lang=$('JARVIS_STT_LANGUAGE').value||'ko-KR';recognition.start()}});$('JARVIS_VAD_THRESHOLD').addEventListener('input',e=>$('thresholdOutput').textContent=Number(e.target.value).toFixed(3));$('JARVIS_VAD_SILENCE_SECONDS').addEventListener('input',e=>$('silenceOutput').textContent=`${Number(e.target.value).toFixed(1)}s`);
$('saveSettings').addEventListener('click',async()=>{const payload={};fields.forEach(id=>{const e=$(id);payload[id]=e.type==='checkbox'?e.checked:e.value});try{await api('/api/settings',{method:'POST',body:JSON.stringify(payload)});$('saveSettings').textContent='SAVED';setTimeout(()=>$('saveSettings').textContent='SAVE',1400)}catch(e){$('saveSettings').textContent='ERROR'}});
async function switchEngine(engine){try{const d=await api('/api/engine',{method:'POST',body:JSON.stringify({engine})});$('engineLabel').textContent=d.engine.toUpperCase();document.querySelectorAll('[data-engine]').forEach(b=>b.classList.toggle('selected',b.dataset.engine===d.engine));$('response').innerHTML='<span class="response-dot"></span><span>'+d.response+'</span>'}catch(e){$('response').innerHTML='<span class="response-dot"></span><span>'+e.message+'</span>'}}
document.querySelectorAll('[data-engine]').forEach(b=>b.addEventListener('click',()=>switchEngine(b.dataset.engine)));
function connectEvents(){try{const socket=new WebSocket(`ws://${location.hostname}:8766`);socket.onmessage=event=>{const message=JSON.parse(event.data);if(message.event==='assistant.state'&&message.data?.state)$('stateLabel').textContent=message.data.state.toUpperCase()};socket.onclose=()=>setTimeout(connectEvents,3000)}catch(e){}}
async function status(){try{const d=await api('/api/status');const active=d.state==='busy';$('stateLabel').textContent=d.tts==='speaking'?'SPEAKING':requestPending?'LOADING':active?'ACTIVE':'STANDBY';$('stateHint').textContent=d.tts==='speaking'?'ELEVENLABS VOICE OUTPUT':requestPending?'WAITING FOR RESPONSE':active?'PROCESSING VOICE SESSION':'DOUBLE CLAP READY';$('orbWrap').classList.toggle('speaking',d.tts==='speaking');$('engineLabel').textContent=d.engine.toUpperCase();document.querySelectorAll('[data-engine]').forEach(b=>b.classList.toggle('selected',b.dataset.engine===d.engine));$('signal').textContent=active?'100':'98';$('clock').textContent=new Date().toLocaleTimeString('en-GB')}catch(e){}}load();loadRuntime();connectEvents();status();setInterval(status,700);setInterval(loadRuntime,5000);